# Generated by Django 4.0.3 on 2023-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_file', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Test_name', models.CharField(max_length=255)),
                ('Test_date', models.DateField()),
                ('Test_time', models.TimeField()),
                ('Status', models.CharField(max_length=255)),
                ('log_file', models.CharField(max_length=255)),
                ('html_report', models.CharField(max_length=255)),
                ('video_file', models.CharField(max_length=255)),
            ],
        ),
    ]
