# Generated by Django 4.0.3 on 2023-10-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataName',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('summary_file', models.CharField(blank=True, db_column='Summary_file', max_length=255, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('test_name', models.CharField(blank=True, db_column='Test_name', max_length=255, null=True)),
                ('test_date', models.DateField(blank=True, db_column='Test_date', null=True)),
                ('test_time', models.TimeField(blank=True, db_column='Test_time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('log_file', models.CharField(blank=True, max_length=255, null=True)),
                ('html_report', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'data_name',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='data_name',
        ),
    ]
