# Generated by Django 4.0.3 on 2023-11-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dataname_delete_data_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataname',
            options={'managed': False, 'ordering': ['time']},
        ),
    ]
